### ISSUE TITLE
9倍圧縮ネザースターを解体できるようにして欲しい

### ISSUE THREAD

**Issue by rikuto0611** [gotochan/BMCPlugin#10]
9倍圧縮ネザースターを解体できるようにして欲しい

**Comment by gotochan** [comment]
I will fix in RecipeManager.

**Comment by gotochan** [comment]
RecipeManagerにて対応予定。

**Comment by gotochan** [comment]
I do commit and push on BMC GitLab, so close this issue.

Thank you issue
