### ISSUE TITLE
ピッケルで掘った♂を自動で焼いてくれる機能がほすぃ…

### ISSUE THREAD

**Issue by rikuto0611** [gotochan/BMCPlugin#14]
ほった鉱石が焼けた状態で出てくるピッケルを作って欲しいです。
エンチャントなどどんなものでもいいのでそういうのも欲しいです！

**Comment by gotochan** [comment]
面白そうな機能なので実装予定。

エンチャント名は後で考える

幸運とかはどうするのかの問題

**Comment by rikuto0611** [comment]
オート住めるティングとかで如何ですか？
幸運やmcmmoで増える分もそのまま焼いて欲しいです！

**Comment by gotochan** [comment]
アイデアありがとうございます。
エンチャント名は Auto Smelt で決定しました。ありがとうございます。

mcmmoの干渉はかなり難しい（私の技量的問題）上、大規模になってしまうので今回は非実装で。

幸運は簡単に取得できるので、幸運については増える分等を調整

<メモ>
math randomで幸運調整、mcの仕様確認
それに準拠
[EnchantmentAPI](http://dev.bukkit.org/bukkit-plugins/enchantmentapi/)を使用するとよさげ。

**Comment by gotochan** [comment]
デバッグ段階。

エンチャントイベントをキャッチし、loreをつけることで対応するというnoobっぷり。

**Comment by gotochan** [comment]
完成しました。サブ鯖に試験導入しておりますのでお試しあれ。

**Comment by rikuto0611** [comment]
本鯖導入はいつ？

2016年4月24日日曜日、Hinyari_Gohan<notifications@github.com>さんは書きました:

**Comment by gotochan** [comment]
バージョン4.0仮のマイルストーン完了時です
