### ISSUE TITLE
粉砕とは逆に圧縮鉄鉱石や圧縮丸石

### ISSUE THREAD

**Issue by rikuto0611** [gotochan/BMCPlugin#17]
圧縮した鉄鉱石、丸石、金鉱石などを作るとブランチマイニングがとてもしやすくなると思います！
倉庫もスッキリすると思うしとてもいいと思います

**Comment by gotochan** [comment]
そのためのバックパックといいますか、エンダーチェストといいますか…
圧縮丸石ぐらいなら実装してもいいかな？

**Comment by rikuto0611** [comment]
それか丸石のみ指定したチェストに送れるなどは？

2016年4月23日土曜日、Hinyari_Gohan<notifications@github.com>さんは書きました:

**Comment by gotochan** [comment]
ストレージボックスのようなものですかね。
そこから置けるようにするとワールドガードAPIを使用する必要

**Comment by rikuto0611** [comment]
倉庫などの既に置いてあるチェストを遠隔で操作するということです

2016年4月24日日曜日、Hinyari_Gohan<notifications@github.com>さんは書きました:

**Comment by gotochan** [comment]
可能といえば可能なのですが少し面倒なのでさらに検討を重ねます。

**Comment by rikuto0611** [comment]
ほーい

2016年4月24日日曜日、Hinyari_Gohan<notifications@github.com>さんは書きました:

**Comment by gotochan** [comment]
別イシューにて対応
